### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by fbertran** [Losswise/losswise-python#3]
I use KerasCallback that way (as described) and losswise 1.0.

import losswise
from losswise.libs import LosswiseKerasCallback

lw_callback = LosswiseKerasCallback(tag='MyProjectTag')
list_callbacks.append(lw_callback)
model.fit(x=X, y=y,
                          validation_split=.2 verbose=2,
                          callbacks=list_callbacks, batch_size=10,
                          epochs=150)

Then I get that error before the training actually starts:

line 14, in on_train_begin
    self.session = Session(tag=self.tag, max_iter=self.max_iter, data=self.data, git_model_path=self.git_model_path)
TypeError: __init__() got an unexpected keyword argument 'data'

I had to edit these to have the callback work :
add a git_model_path argument (unused later) to the Session init in __init__.py

class Session(object):
    def __init__(self, tag=None, max_iter=None, params={}, git_model_path={}):

modify the call to Session in libs.py and replace data by params.
        self.session = Session(tag=self.tag, max_iter=self.max_iter, params=self.data, git_model_path=self.git_model_path)

Can you fix the code please or explain me how it should be used ?
Best.

**Comment by nicodjimenez** [comment]
Super sorry about this, thanks a lot for pointing out this error.  There was a deprecated `data` parameter for `Sessions` that was replaced by the `params` input argument.  Will add tests so that we don't break old code in the future.  Btw I definitely recommend using the `params` field (e.g `LosswiseKerasCallback(tag='MyProjectTag', params={'gpu': 0, 'dropout': 0.1})`) it's now supported by our UI and very useful - at least I find it useful to keep track of things.

**Comment by fbertran** [comment]
Did you also fix the git_model_path issue ? It also raises an unexpected argument.
